### ISSUE TITLE
Passwords for the demo users

### ISSUE THREAD

**Issue by sla-te** [byronlara5/django_onlyfans_clone_youtube#2]
![image](https://user-images.githubusercontent.com/22568014/124269281-fc280780-db3a-11eb-9a61-ad5f59804a8b.png)

**Comment by sla-te** [comment]
admin: demo or admin:demo1234 doesn't work

**Comment by ryhyd** [comment]
Figured out it is admin:admin1234 for the admin account. For the other users, you can copy the hash of the admin user and reuse the admin1234 password.
